# Python plugin definition
refs:
    # TODO: Add base plugin reference
    - python.yml    # Python path contribution
    - files.yml     # Look for python source files
    - version.yml   # Python version contribution
    - setup.yml     # Python setup files generation
    - format.yml    # Python code format (with black/isort)
    - flake.yml     # Python code analysis (with flake8)
    - build.yml     # Python module build/install
